<?php


/**
 * Implements hook_menu().
 */
function theme_switcher_menu() {
  $items['admin/school/theme_switcher'] = array(
    'title' => 'Theme',
    'description' => 'Switch theme',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('theme_switcher_settings_page'),
    'access arguments' => array('administer nodes'),
  );
  $items['admin/config/school/theme_switcher_admin'] = array(
    'title' => 'Theme switching admin',
    'description' => 'Switch theme',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('theme_switcher_settings_admin_page'),
    'access arguments' => array('administer theme switching'),
  );
  return $items;
}



/**
 * Set the theme
 *
 */
function theme_switcher_custom_theme() {
  global $theme_key;
  //if ($some_condition_is_true) {
    return variable_get('school_theme', $theme_key);
  //}
}


/**
 * Theme switching page
 */
function theme_switcher_settings_page($form, &$form_state) {
  global $base_url;
  global $theme_key;
  $options = variable_get('school_enabled_themes',array());
  $options = array_filter($options);
  $form['school_theme'] = array(
    '#type' => 'select',
    '#title' => t('Select Theme'),
    '#default_value' => variable_get('school_theme',$theme_key),
    '#options' => $options,
    '#attributes' => array(
      'placeholder' => '',
    ),
  );
  if (user_access('administer features')) {
    $form['link_to_admin'] = array(
      '#markup' => '<a href="/admin/config/school/theme_switcher_admin">Manage themes that can be enabled here.</a>'
    );
  }

  return system_settings_form($form);
}


/**
 * Theme switching page
 */
function theme_switcher_settings_admin_page($form, &$form_state) {
  global $base_url;
  $themes = list_themes();
  foreach($themes as $name => $theme) {
    $options[$name] = $theme->name;
  }
  $theme_options = array();
  $form['school_enabled_themes'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Enable themes'),
    '#default_value' => variable_get('school_enabled_themes',array()),
    '#options' => $options,
    '#checkboxes' => true,
    '#attributes' => array(
      'placeholder' => '',
    ),
  );

  return system_settings_form($form);
}
